// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzwh9Tp1aEa-IlV0J2xg9BubAgedK7VP0',
    appId: '1:738334950926:web:eaa3892d0f3e3d2f90de5f',
    messagingSenderId: '738334950926',
    projectId: 'cropkart-6461c',
    authDomain: 'cropkart-6461c.firebaseapp.com',
    storageBucket: 'cropkart-6461c.firebasestorage.app',
    measurementId: 'G-008N5EPK4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2BxAGj4ghwZnhDbXwA5ZjnBQLxDd8qmg',
    appId: '1:738334950926:android:b2bae1cf0d368cfd90de5f',
    messagingSenderId: '738334950926',
    projectId: 'cropkart-6461c',
    storageBucket: 'cropkart-6461c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzwh9Tp1aEa-IlV0J2xg9BubAgedK7VP0',
    appId: '1:738334950926:web:5b5a366f94b8720990de5f',
    messagingSenderId: '738334950926',
    projectId: 'cropkart-6461c',
    authDomain: 'cropkart-6461c.firebaseapp.com',
    storageBucket: 'cropkart-6461c.firebasestorage.app',
    measurementId: 'G-66VLR2KMCJ',
  );

}